name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: nvidia/cuda:12.3.2-devel-ubuntu22.04
      options: --gpus all

    steps:
    - uses: actions/checkout@v3             

    # Note: The CUDA toolkit is already included in the container image, so we don't need the Jimver/cuda-toolkit action anymore.

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
